# Generated by Django 6.1 on 2026-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="classroom",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mon", "월"),
                    ("tue", "화"),
                    ("wed", "수"),
                    ("thu", "목"),
                    ("fri", "금"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
