# Generated by Django 6.1 on 2026-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=15, help_text="세션이 자동으로 마감되기까지의 시간(분)"
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="late_after_minutes",
            field=models.PositiveIntegerField(
                default=5, help_text="이 시간(분) 이후 체크인은 지각으로 처리"
            ),
        ),
    ]
